name: speech_to_text_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  speech_to_text: 5.1.0
  highlight_text: ^1.3.0
  avatar_glow: ^2.0.2
  url_launcher: ^6.0.16
  clipboard: ^0.1.3
  http: ^0.13.4
  dialog_flowtter: ^0.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true